spring:
  application:
    name: synapse

  datasource:
    url: jdbc:postgresql://localhost:5432/synapse
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: test

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate # Now hibernate won't create the schema on its own during app startup.
    properties:
      hibernate:
        format_sql=true

#------------flyway------------
  flyway:
    enabled: true


#-----------Actuator--------------
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always