-- Enable UUID generation function (only needed once per database)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
--Creating Users table
-- UUIDs are generated by Hibernate during normal application flow.
-- DEFAULT gen_random_uuid() exists only as a fallback for manual SQL inserts or administrative scripts.
CREATE TABLE users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name      VARCHAR(255) NOT NULL,
    last_name       VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password        VARCHAR(255) NOT NULL,
    phone_number    VARCHAR(20),
    role            VARCHAR(50) NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index on email since it's used for lookups (login) very frequently
--CREATE INDEX idx_users_email ON users(email);-- doing this is redundant bcoz Postgresql already creates an index for
--columns marked with "UNIQUE".